# -- User definitions ---------------------------

HAL_PATH = ../../../HAL
APP_NAME = ClockPrescaler

BOARD = EASYAVR128

INCLUDES = \
  -I .

SRCS = \
  ClockPrescaler.cpp

include $(HAL_PATH)/build.make
