# -- User definitions ---------------------------

HAL_PATH = ../../../HAL
APP_NAME = DigitalIO

BOARD = ARDUINOMEGA2560

INCLUDES = \
  -I .

SRCS = \
  DigitalIO.cpp


include $(HAL_PATH)/build.make