# -- User definitions ---------------------------

HAL_PATH = ../../../HAL
APP_NAME = ADC-noise-reduction

BOARD = EASYAVR128

INCLUDES = \
  -I .

SRCS = \
  ADC-noise-reduction.cpp

include $(HAL_PATH)/build.make
